### PR TITLE
Support ppc64le for CUDA 10.2

### LINKED ISSUE #6: Build for ppc64le

### PR DESCRIPTION
**Pull request by leofang**
Close #6.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
```
/usr/bin/which: no cuda-gdb in (/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_build_env/bin:/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_build_env:/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_build_env/bin:/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl:/home/conda/feedstock_root/build_artifacts/cutensor_1622660207840/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin)
Cannot determine CUDA_HOME: cuda-gdb not in PATH
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=332029&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3&l=147

@jaimergp Is something wrong with nvcc's activate script on ppc64le?

**Comment by jaimergp** [comment]
The problem is more on the Docker image side. For some reason, /usr/local/cuda/bin is not on PATH, despite https://github.com/conda-forge/docker-images/pull/181

See workarounds in https://github.com/conda-forge/openmm-feedstock/pull/55/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR23

**Comment by leofang** [comment]
Ah nice, thanks @jaimergp for pointer!

**Comment by leofang** [comment]
hmmm...The compiler flags work on x86-64 but not on ppc64le...
```
++ nvcc -Xcompiler -mno-float128 -I/home/conda/feedstock_root/build_artifacts/cutensor_1622774225568/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -L/home/conda/feedstock_root/build_artifacts/cutensor_1622774225568/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -lcutensor contraction.cu -o contraction
+ error_log='/home/conda/feedstock_root/build_artifacts/cutensor_1622774225568/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/../lib/gcc/powerpc64le-conda-linux-gnu/8.4.0/../../../../powerpc64le-conda-linux-gnu/bin/ld: contraction: hidden symbol `cudaLaunchKernel'\'' in /usr/local/cuda/bin/../targets/ppc64le-linux/lib/libcudart_static.a(libcudart_static.a.o) is referenced by DSO
/home/conda/feedstock_root/build_artifacts/cutensor_1622774225568/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/../lib/gcc/powerpc64le-conda-linux-gnu/8.4.0/../../../../powerpc64le-conda-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status'
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=332796&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3&l=320

**Comment by leofang** [comment]
@jaimergp Thanks again! 😁

**Pull request merged**
